export type WarnTemplate = {
  name: string;
  description: string;
  params: {
    type: "input";
    name: string;
    id: string;
    required: boolean;
    placeholder: string;
    defaultValue?: string;
  }[];
  category: string;
  nosubst?: boolean;
} & ({ hasTitle: true } | { hasTitle: false; defaultTitle: string });

function warnInput(
  name: string,
  id: string,
  required: boolean,
  placeholder: string,
): WarnTemplate["params"][number] {
  return { type: "input", name, id, required, placeholder };
}

export const WARN_TEMPLATES = [
  {
    name: "Welcome",
    description: "新規利用者への歓迎",
    hasTitle: false,
    defaultTitle: "ウィキペディアへようこそ！",
    params: [],
    category: "ようこそ",
  },
  {
    name: "アカウント作成のお願い",
    description: "よく活動してるIPユーザーにアカウント作成を促す案内",
    hasTitle: false,
    defaultTitle: "アカウント作成のお願い",
    params: [],
    category: "ようこそ",
    nosubst: true,
  },
  {
    name: "Test0",
    description: "テキストを消してしまった場合の案内",
    hasTitle: false,
    defaultTitle: "ご案内",
    params: [
      {
        type: "input",
        name: "項目名",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
      {
        type: "input",
        name: "追加メッセージ",
        id: "2",
        required: false,
        placeholder: "「ご参照ください。」の後ろのメッセージ",
      },
    ],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Selftest",
    description: "テスト投稿を自分で差し戻した人に対しての案内",
    hasTitle: false,
    defaultTitle: "ご案内",
    params: [],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Test1",
    description: "テスト投稿の案内",
    hasTitle: false,
    defaultTitle: "ご案内",
    params: [
      {
        type: "input",
        name: "項目名",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Test2",
    description: "荒らしの注意 (もしくはTestで注意後)",
    hasTitle: false,
    defaultTitle: "注意",
    params: [
      {
        type: "input",
        name: "項目名",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Test2a",
    description: "白紙化や記述除去荒らしの注意",
    hasTitle: false,
    defaultTitle: "注意",
    params: [
      {
        type: "input",
        name: "項目名",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Test3",
    description: "荒らしの警告",
    hasTitle: false,
    defaultTitle: "警告",
    params: [
      {
        type: "input",
        name: "項目名",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Test4",
    description: "荒らし行為への最後の警告",
    hasTitle: false,
    defaultTitle: "最終警告",
    params: [
      {
        type: "input",
        name: "項目名",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Test",
    description: "通常のページでのテスト投稿に対する案内",
    hasTitle: false,
    defaultTitle: "ご案内",
    params: [warnInput("テスト投稿を行ったページ", "1", false, "ほげほげ")],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Uw-disruptive1",
    description: "非建設的な編集に対する初回の案内",
    hasTitle: false,
    defaultTitle: "ご案内",
    params: [],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Uw-disruptive2",
    description: "破壊的に見える編集に対する注意",
    hasTitle: false,
    defaultTitle: "注意",
    params: [],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Uw-disruptive3",
    description: "破壊的な編集を続ける利用者への警告",
    hasTitle: false,
    defaultTitle: "警告",
    params: [],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Uw3",
    description: "破壊的な編集を続ける利用者への警告",
    hasTitle: false,
    defaultTitle: "警告",
    params: [],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Uw4",
    description: "破壊的な編集に対する最終警告",
    hasTitle: false,
    defaultTitle: "最終警告",
    params: [],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Warn2",
    description: "荒らし相当の行為に対するレベル2の警告",
    hasTitle: false,
    defaultTitle: "注意",
    params: [warnInput("問題のある投稿を行ったページ", "1", false, "ほげほげ")],
    category: "Test (一般的なテストもしくは荒らし)",
  },
  {
    name: "Preview",
    description: "プレビューの案内",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "何回目？",
        id: "1",
        required: false,
        placeholder: "3回目",
      },
    ],
    category: "一括投稿・プレビュー",
  },
  {
    name: "PreviewMobile",
    description: "プレビューの案内 (モバイル)",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "何回目？",
        id: "1",
        required: false,
        placeholder: "3回目",
      },
    ],
    category: "一括投稿・プレビュー",
  },
  {
    name: "一括",
    description: "一括投稿の案内",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "何回目？",
        id: "1",
        required: false,
        placeholder: "3回目",
      },
    ],
    category: "一括投稿・プレビュー",
  },
  {
    name: "一括Preview",
    description: "一括投稿とプレビュー案内の組み合わせ",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "何回目？",
        id: "1",
        required: false,
        placeholder: "3回目",
      },
    ],
    category: "一括投稿・プレビュー",
  },
  {
    name: "Sign",
    description: "署名の案内",
    hasTitle: true,
    params: [],
    category: "コミュニケーション関係",
  },
  {
    name: "Attack",
    description: "利用者に対する個人攻撃の警告",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "問題のある投稿を行ったページ",
        id: "1",
        required: false,
        placeholder: "ノート:ほげほげ",
      },
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "Edit war",
    description: "編集合戦への警告",
    hasTitle: false,
    defaultTitle: "編集合戦はおやめください",
    params: [],
    category: "コミュニケーション関係",
  },
  {
    name: "Notchat",
    description: "ノートページで私的な会話を続ける利用者に対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "ページ名",
        id: "1",
        required: false,
        placeholder: "利用者‐会話:ウィキ助",
      },
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "Talk reject",
    description: "対話を拒否する利用者への警告",
    hasTitle: false,
    defaultTitle: "対話拒否はおやめください",
    params: [
      {
        type: "input",
        name: "対話拒否を行ったページ",
        id: "1",
        required: false,
        placeholder: "ノート:ほげほげ",
      },
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "発言改竄",
    description: "発言改竄に対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "改竄されたページ",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "Sign2",
    description: "無署名のコメントに対する署名のお願い",
    hasTitle: true,
    params: [
      warnInput("コメントを投稿したページ", "1", true, "ノート:ほげほげ"),
      warnInput("投稿版の oldid", "2", true, "123456789"),
      warnInput("投稿時刻", "3", true, "2026年8月4日 (火) 12:00 (UTC)"),
      warnInput("自分の署名", "4", false, "~~~~"),
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "Talk reject 2",
    description: "対話拒否を続ける利用者への最終警告",
    hasTitle: false,
    defaultTitle: "対話拒否についての最終警告",
    params: [],
    category: "コミュニケーション関係",
  },
  {
    name: "Uw-notvand",
    description: "荒らしでない編集を荒らしと扱った利用者への案内",
    hasTitle: false,
    defaultTitle: "荒らしの扱いについて",
    params: [
      warnInput("対象の記事", "1", false, "ほげほげ"),
      warnInput("末尾のメッセージ", "2", false, "ありがとうございます。"),
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "一般警告テンプレート貼付中止のお願い",
    description:
      "モバイル利用者への不適切な一般警告テンプレート貼付に対する注意",
    hasTitle: true,
    params: [
      warnInput("警告を受けたモバイル利用者名", "1", true, "Example"),
      warnInput("貼付されたテンプレート名", "2", true, "Preview"),
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "会話ページの目的外利用",
    description: "ノートページや会話ページの目的外利用に対する警告",
    hasTitle: false,
    defaultTitle: "会話ページの目的外利用はおやめください",
    params: [],
    category: "コミュニケーション関係",
  },
  {
    name: "要約欄の目的外利用",
    description: "要約欄での会話や意見表明などの目的外利用に対する注意",
    hasTitle: true,
    params: [],
    category: "コミュニケーション関係",
  },
  {
    name: "利用者名変更のお願い",
    description: "混同のおそれや不適切な利用者名に対する変更依頼",
    hasTitle: true,
    params: [
      warnInput("変更を求める理由の種類", "1", true, "1 / 2 / 3"),
      warnInput("類似利用者名または具体的な理由", "2", false, "Example2"),
    ],
    category: "コミュニケーション関係",
  },
  {
    name: "Spam",
    description: "宣伝投稿への注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "冒頭文",
        id: "1",
        required: false,
        placeholder: "あなたの[[記事]]における編集を拝見致しました。",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "荒らしの差し戻し",
    description: "過剰な荒らしの差し戻しに対する警告",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "差し戻しを繰り返したページ",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
      {
        type: "input",
        name: "何回目?",
        id: "nth",
        required: false,
        placeholder: "3",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "ご自身の記事",
    description: "利用者自身の記事の作成・編集に対する注意 (確信がない場合)",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "編集したページ",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "ご自身の記事2",
    description: "利用者自身の記事の作成に対する注意 (明白な場合)",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "作成したページ",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "機械翻訳の濫用",
    description: "機械翻訳の濫用に対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "翻訳されたページ",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
      {
        type: "input",
        name: "使用された機械翻訳 (推定)",
        id: "2",
        required: true,
        placeholder: "Google翻訳",
        defaultValue: "Google翻訳",
      },
      {
        type: "input",
        name: "不自然な表現の例",
        id: "3",
        required: true,
        placeholder:
          "「アルコール使用は主に男の人口の間で高かった」「急いで混雑していました」",
      },
      {
        type: "input",
        name: "全般8 (初版投稿者依頼 )が適用可能→1、削除依頼提出済み→2を入力",
        id: "4",
        required: false,
        placeholder: "2",
      },
      {
        type: "input",
        name: "削除依頼ページ",
        id: "5",
        required: false,
        placeholder: "[[Wikipedia:削除依頼/記事名]]",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "Uw-ai1",
    description: "AI生成コンテンツの注意",
    hasTitle: false,
    defaultTitle: "大規模言語モデルの利用について",
    params: [
      {
        type: "input",
        name: "対象ページ",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "丸写し",
    description: "主に外部サイトからの丸写しの注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "丸写しされた記事名",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
      {
        type: "input",
        name: "コピー元",
        id: "2",
        required: true,
        placeholder: "[URL ページ名]",
      },
      {
        type: "input",
        name: "削除依頼提出済み→削除依頼サブページ名、全般9→「即時削除」を入力",
        id: "3",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "スタブ未満作成停止のお願い",
    description: "短すぎる記事作成の繰り返しの注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "何回目?",
        id: "1",
        required: false,
        placeholder: "3回目",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "記述除去",
    description: "記述の無断除去に対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "除去されたページ",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "翻訳継承",
    description: "翻訳継承ができていない場合の案内",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "翻訳されたページ",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
      {
        type: "input",
        name: "翻訳元",
        id: "2",
        required: true,
        placeholder: "[[:en:Main_Page]]",
      },
      {
        type: "input",
        name: "削除依頼提出済み→1、削除依頼提出をお願い→2を入力",
        id: "3",
        required: false,
        placeholder: "1",
      },
      {
        type: "input",
        name: "削除依頼ページ",
        id: "4",
        required: false,
        placeholder: "[[Wikipedia:削除依頼/記事名]]",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "出典提示のお願い",
    description: "出典を明記しない利用者に対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "ページ名",
        id: "1",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "特筆性のない記事の作成停止のお願い",
    description: "特筆性のない記事の作成の繰り返しの注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "何回目?",
        id: "1",
        required: false,
        placeholder: "3回目",
      },
    ],
    category: "投稿内容関係",
  },
  {
    name: "Contrib-en1",
    description: "日本語版に英語で投稿した利用者への案内",
    hasTitle: false,
    defaultTitle: "日本語での投稿のお願い",
    params: [],
    category: "投稿内容関係",
  },
  {
    name: "テンプレート除去",
    description:
      "問題を解決せずメンテナンス用テンプレートを除去した利用者への注意",
    hasTitle: true,
    params: [
      warnInput("テンプレートを除去した記事", "1", true, "ほげほげ"),
      warnInput("除去したテンプレート名", "2", true, "出典の明記"),
      warnInput("何回目のお願いか", "3", false, "2"),
    ],
    category: "投稿内容関係",
  },
  {
    name: "記事名の付け方違反",
    description: "記事名の付け方に違反した記事の移動通知",
    hasTitle: true,
    params: [
      warnInput("移動元の記事名", "1", true, "ほげほげ"),
      warnInput("移動先の記事名", "2", true, "ほげほげほげ"),
      warnInput("削除依頼に提出済み", "3", false, "1"),
    ],
    category: "投稿内容関係",
  },
  {
    name: "赤リンク削除",
    description: "ローカルルールによる未作成エントリの除去通知",
    hasTitle: true,
    params: [
      warnInput(
        "エントリを追加した一覧ページ名",
        "1",
        true,
        "ギタリストの一覧",
      ),
      warnInput(
        "議論を行うノートページ名",
        "2",
        false,
        "ノート:ギタリストの一覧",
      ),
    ],
    category: "投稿内容関係",
  },
  {
    name: "赤リンク追加",
    description:
      "ローカルルールのある一覧へ未作成エントリを追加した利用者への注意",
    hasTitle: true,
    params: [
      warnInput(
        "エントリを追加した一覧ページ名",
        "1",
        true,
        "ギタリストの一覧",
      ),
      warnInput(
        "議論を行うノートページ名",
        "2",
        false,
        "ノート:ギタリストの一覧",
      ),
    ],
    category: "投稿内容関係",
  },
  {
    name: "体験談加筆の中止のお願い",
    description: "個人的な体験談の加筆を繰り返す利用者への中止依頼",
    hasTitle: true,
    params: [],
    category: "投稿内容関係",
  },
  {
    name: "提案手順不備",
    description: "分割・統合・改名提案の手順不備に対する案内",
    hasTitle: true,
    params: [
      warnInput(
        "提案の種類",
        "1",
        true,
        "分割1 / 分割2 / 統合1 / 統合2 / 改名1 / 改名2",
      ),
      warnInput("提案対象の記事名", "2", true, "ほげほげ"),
    ],
    category: "投稿内容関係",
  },
  {
    name: "不適切な概要節",
    description: "導入部の直後を安易に概要節とした編集への注意",
    hasTitle: true,
    params: [],
    category: "投稿内容関係",
  },
  {
    name: "目撃情報加筆の中止のお願い",
    description: "個人的な目撃情報の加筆に対する中止依頼",
    hasTitle: true,
    params: [],
    category: "投稿内容関係",
  },
  {
    name: "Blp0",
    description: "存命人物に関する記事を編集する際の案内",
    hasTitle: false,
    defaultTitle: "存命人物に関する記事の編集について",
    params: [],
    category: "出典・検証可能性",
  },
  {
    name: "Blp1",
    description: "存命人物への無出典の否定的記述に対する警告",
    hasTitle: false,
    defaultTitle: "存命人物に関する記事の編集について",
    params: [warnInput("問題のある投稿を行ったページ", "1", false, "ほげほげ")],
    category: "出典・検証可能性",
  },
  {
    name: "Blp2",
    description: "存命人物への無出典の否定的記述に対する最終警告",
    hasTitle: false,
    defaultTitle: "存命人物に関する記事の編集について",
    params: [],
    category: "出典・検証可能性",
  },
  {
    name: "Uw-badsourced",
    description: "信頼できない情報源の使用に対する警告",
    hasTitle: false,
    defaultTitle: "信頼できる情報源のお願い",
    params: [warnInput("問題のある編集を行ったページ", "1", true, "ほげほげ")],
    category: "出典・検証可能性",
  },
  {
    name: "Uw-pretense",
    description: "出典にない内容を加筆した利用者への警告",
    hasTitle: false,
    defaultTitle: "出典に基づく記述のお願い",
    params: [
      warnInput(
        "問題のある編集の版指定リンク",
        "1",
        true,
        "{{特定版|ほげほげ|123456789}}",
      ),
    ],
    category: "出典・検証可能性",
  },
  {
    name: "Uw-unsourced1",
    description: "出典のない加筆に対する初回の案内",
    hasTitle: false,
    defaultTitle: "出典明記のお願い",
    params: [],
    category: "出典・検証可能性",
  },
  {
    name: "Uw-unsourced2",
    description: "出典のない加筆に対する注意",
    hasTitle: false,
    defaultTitle: "出典明記のお願い",
    params: [],
    category: "出典・検証可能性",
  },
  {
    name: "Uw-unsourced3",
    description: "出典のない加筆を続ける利用者への警告",
    hasTitle: false,
    defaultTitle: "警告",
    params: [],
    category: "出典・検証可能性",
  },
  {
    name: "Uw-unsourced4",
    description: "出典のない加筆を続ける利用者への最終警告",
    hasTitle: false,
    defaultTitle: "最終警告",
    params: [],
    category: "出典・検証可能性",
  },
  {
    name: "医学の情報源のお願い",
    description: "医学情報に適した信頼できる二次資料の提示依頼",
    hasTitle: true,
    params: [],
    category: "出典・検証可能性",
  },
  {
    name: "出典除去",
    description: "他の利用者が明記した出典の理由なき除去に対する注意",
    hasTitle: true,
    params: [warnInput("出典を除去した記事", "1", false, "ほげほげ")],
    category: "出典・検証可能性",
  },
  {
    name: "存命人物への無出典記述",
    description: "存命人物記事への無出典記述を除去したことの通知と注意",
    hasTitle: true,
    params: [warnInput("対象となった存命人物記事", "1", true, "ほげほげ")],
    category: "出典・検証可能性",
  },
  {
    name: "二次資料提示のお願い",
    description: "一次資料に依存した投稿への二次資料の提示依頼",
    hasTitle: true,
    params: [warnInput("投稿が行われたページ", "1", false, "ほげほげ")],
    category: "出典・検証可能性",
  },
  {
    name: "コピー&ペースト中止のお願い",
    description: "履歴を継承しないコピー&ペーストによる改名の中止依頼",
    hasTitle: true,
    params: [warnInput("ログイン利用者向けの案内を省略", "1", false, "1")],
    category: "著作権・履歴",
  },
  {
    name: "参考文献提示のお願い",
    description: "転載のおそれがある投稿への参考文献の提示依頼",
    hasTitle: true,
    params: [],
    category: "著作権・履歴",
  },
  {
    name: "分割手順の遵守のお願い",
    description: "履歴を継承しない記事分割の中止依頼",
    hasTitle: true,
    params: [warnInput("提出済みの削除依頼名", "1", false, "ほげほげ")],
    category: "著作権・履歴",
  },
  {
    name: "翻訳版補遺のご案内",
    description: "翻訳時の履歴不継承に対する要約欄での補遺方法の案内",
    hasTitle: true,
    params: [
      warnInput("履歴不継承が発生した記事名", "1", true, "ほげほげ"),
      warnInput("新規記事ではなく翻訳加筆", "2", false, "加筆"),
      warnInput("履歴補遺の補足説明を省略", "3", false, "1"),
      warnInput("複数回貼付時の短縮表示", "4", false, "yes"),
    ],
    category: "著作権・履歴",
  },
  {
    name: "履歴不継承",
    description: "要約欄に転記元と版が記載されていない履歴不継承の通知",
    hasTitle: true,
    params: [
      warnInput("履歴不継承が発生した記事名", "1", true, "ほげほげ"),
      warnInput("提出済みの削除依頼名", "2", false, "ほげほげ"),
    ],
    category: "著作権・履歴",
  },
  {
    name: "削除依頼タグ除去",
    description: "削除依頼タグの除去に対する注意",
    hasTitle: false,
    defaultTitle: "削除依頼タグの除去について",
    params: [
      {
        type: "input",
        name: "削除依頼タグが除去されたページ",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
    ],
    category: "削除関係",
  },
  {
    name: "不当な即時削除タグ除去",
    description: "即時削除タグの不当な除去の繰り返しに対する注意",
    hasTitle: false,
    defaultTitle: "即時削除タグの除去について",
    params: [
      {
        type: "input",
        name: "ページ名",
        id: "1",
        required: true,
        placeholder: "ほげほげ",
      },
    ],
    category: "削除関係",
  },
  {
    name: "即時削除の乱用",
    description: "即時削除の乱用に対する注意",
    hasTitle: true,
    params: [],
    category: "削除関係",
  },
  {
    name: "リンク先削除",
    description: "リンク先の削除に伴う一覧ページからのエントリ除去の通知",
    hasTitle: true,
    params: [
      warnInput("一覧ページ名", "1", true, "ギタリストの一覧"),
      warnInput("削除されたページ名", "2", true, "ほげほげ"),
      warnInput("削除依頼のサブページ名", "3", false, "ほげほげ"),
    ],
    category: "削除関係",
  },
  {
    name: "コモンズへの移動通知",
    description: "ファイルをウィキメディア・コモンズへ移動したことの通知",
    hasTitle: true,
    params: [
      warnInput("日本語版でのファイル名", "1", true, "Example.jpg"),
      warnInput("コモンズでのファイル名", "2", false, "Example.jpg"),
    ],
    category: "画像関係",
  },
  {
    name: "画像のお願い",
    description: "撮影者・出典とライセンス・ファイル名の不備に対する改善依頼",
    hasTitle: true,
    params: [
      warnInput("文言の種類", "1", true, "a / s / n"),
      warnInput("問題のあるファイル名", "2", true, "Example.jpg"),
    ],
    category: "画像関係",
  },
  {
    name: "画像除去",
    description: "他の利用者がアップロードした画像の理由なき除去に対する注意",
    hasTitle: true,
    params: [warnInput("画像を除去した記事", "1", false, "ほげほげ")],
    category: "画像関係",
  },
  {
    name: "Image copyright",
    description: "著作権の状態が不明な画像のアップロードに対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "画像名",
        id: "1",
        required: true,
        placeholder: "ほげほげ.png",
      },
    ],
    category: "画像の著作権",
  },
  {
    name: "Image pubart",
    description: "屋外美術画像のアップロード方針違反に対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "画像名",
        id: "1",
        required: true,
        placeholder: "ほげほげ.png",
      },
    ],
    category: "画像の著作権",
  },
  {
    name: "Image source",
    description: "画像の出典・ライセンス明記を求める注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "画像名",
        id: "1",
        required: true,
        placeholder: "ほげほげ.png",
      },
    ],
    category: "画像の著作権",
  },
  {
    name: "Image URAA",
    description:
      "日本で著作権が消滅し米国で著作権がある画像方針違反に対する注意",
    hasTitle: true,
    params: [
      {
        type: "input",
        name: "画像名",
        id: "1",
        required: true,
        placeholder: "ほげほげ.png",
      },
    ],
    category: "画像の著作権",
  },
  {
    name: "メールを送りました",
    description: "ウィキメール送信の通知",
    hasTitle: false,
    defaultTitle: "ウィキメールを送りました",
    params: [
      {
        type: "input",
        name: "件名",
        id: "subject",
        required: false,
        placeholder: "ほげほげ",
      },
    ],
    category: "その他",
    nosubst: true,
  },
  {
    name: "警告",
    description: "任意の文章を表示する汎用的な警告ボックス",
    hasTitle: false,
    defaultTitle: "警告",
    params: [warnInput("警告文", "1", true, "ここに警告文を入力")],
    category: "その他",
    nosubst: true,
  },

  // 投稿ブロック通知は管理者権限が必要なため無効
  /*
  {
    name: "3rr",
    description: "過度の差し戻しによる投稿ブロックの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [warnInput("編集合戦を行ったページ", "1", true, "ほげほげ")],
    category: "投稿ブロック",
  },
  {
    name: "Block-reset",
    description: "ログイン利用者のブロック回避による期間リセットの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロック期間リセットのお知らせ",
    params: [],
    category: "投稿ブロック",
  },
  {
    name: "Block-reset-ip",
    description: "IP利用者のブロック回避による期間リセットの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロック期間リセットのお知らせ",
    params: [],
    category: "投稿ブロック",
  },
  {
    name: "Blocked",
    description: "ログイン利用者への有期ブロックの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [
      warnInput("投稿ブロック依頼のサブページ名", "1", false, "利用者:例"),
      warnInput("「編集」の代替表現", "2", false, "投稿"),
    ],
    category: "投稿ブロック",
  },
  {
    name: "Blocked-ip",
    description: "IP利用者への有期ブロックの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [],
    category: "投稿ブロック",
  },
  {
    name: "Checkuserblock-account",
    description: "チェックユーザーによる多重アカウントの無期限ブロック通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [
      warnInput("追加コメント", "1", false, "調査結果に関するコメント"),
      warnInput("署名", "sig", false, "--~~~~"),
    ],
    category: "投稿ブロック",
  },
  {
    name: "Checkuserblock-account/sandbox",
    description: "チェックユーザーによるブロック通知のサンドボックス版",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [
      warnInput("追加コメント", "1", false, "調査結果に関するコメント"),
      warnInput("署名", "sig", false, "--~~~~"),
    ],
    category: "投稿ブロック",
  },
  {
    name: "ILLEGIT",
    description: "多重アカウントの不適切な使用による無期限ブロックの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [],
    category: "投稿ブロック",
  },
  {
    name: "Infiniteblocked",
    description: "ログイン利用者への無期限ブロックの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [
      warnInput("投稿ブロック依頼のサブページ名", "1", false, "利用者:例"),
    ],
    category: "投稿ブロック",
  },
  {
    name: "SharedaccountBlocked",
    description: "パスワード公開による共有アカウントの無期限ブロック通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [],
    category: "投稿ブロック",
  },
  {
    name: "Sockblock",
    description: "ブロック回避で作成されたアカウントへの無期限ブロック通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [warnInput("ブロック中のアカウント名", "1", true, "Example")],
    category: "投稿ブロック",
  },
  {
    name: "Sockblock-ip",
    description: "ブロック回避に使用されたIPアドレスへのブロック通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [warnInput("ブロック中のアカウント名", "1", true, "Example")],
    category: "投稿ブロック",
  },
  {
    name: "Spamblocked",
    description: "スパム行為による有期ブロックの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [
      warnInput("ブロック期間", "1", false, "2週間"),
      warnInput("スパム行為のあったページなど", "2", false, "[[ほげほげ]]で"),
    ],
    category: "投稿ブロック",
  },
  {
    name: "Spamblocked/無期限",
    description: "スパム行為による無期限ブロックの通知",
    hasTitle: false,
    defaultTitle: "投稿ブロックのお知らせ",
    params: [
      warnInput("スパム行為のあったページなど", "1", false, "[[ほげほげ]]で"),
    ],
    category: "投稿ブロック",
  }
  */
] as const satisfies WarnTemplate[];
